# Generated by Django 4.0.4 on 2022-05-22 19:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('person', models.CharField(max_length=100, null=True, verbose_name='Person')),
                ('taxnumber', models.CharField(max_length=100, null=True, verbose_name='Tax Number')),
                ('address', models.TextField(max_length=300, null=True, verbose_name='Address')),
                ('telephone', models.CharField(max_length=100, null=True, verbose_name='Tel')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='Email')),
                ('bankAccount', models.CharField(max_length=100, null=True, verbose_name='Bank Account')),
            ],
        ),
    ]
