# Generated by Django 4.0.4 on 2022-05-21 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('href', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=50, null=True, verbose_name='Key')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=50, null=True, verbose_name='Name')),
                ('description', models.TextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Price')),
                ('stock', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('images', models.ManyToManyField(to='product.image')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
