# Generated by Django 4.0.4 on 2022-05-21 21:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('person', models.CharField(max_length=100, null=True, verbose_name='Person')),
                ('taxnumber', models.CharField(max_length=100, null=True, verbose_name='Tax Number')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.customer'),
        ),
    ]
