# Generated by Django 4.0.4 on 2022-05-22 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='href',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.customer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(default='<django.db.models.fields.CharField>_81SQ', max_length=50, null=True, unique=True, verbose_name='Key'),
        ),
    ]
