# Generated by Django 4.0.4 on 2022-05-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_image_href_alter_product_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(null=True, to='product.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='key',
            field=models.CharField(default='<bound method Field.value_to_string of <django.db.models.fields.CharField>>_A94N', editable=False, max_length=50, null=True, unique=True, verbose_name='Key'),
        ),
    ]
