# Generated by Django 4.0.4 on 2022-05-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_customer'),
        ('product', '0009_remove_product_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
