# Generated by Django 4.0.4 on 2022-05-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Products'},
        ),
    ]
