# Generated by Django 4.0.4 on 2022-05-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='key',
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(default='p_fkvt', max_length=50, null=True, verbose_name='Code'),
        ),
    ]
