# Generated by Django 4.0.4 on 2022-05-26 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_rename_title_product_name_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='P_4Y0B', max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
