# Generated by Django 4.0.4 on 2022-05-26 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Code'),
        ),
    ]
