# Generated by Django 4.0.4 on 2022-05-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(to='order.orderitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CP', 'Completed'), ('DE', 'Delivered'), ('RB', 'Returned Back'), ('CA', 'Cancelled')], default=('NS', 'Not Started'), max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Started'), ('IP', 'In Progress'), ('CP', 'Completed'), ('DE', 'Delivered'), ('RB', 'Returned Back'), ('CA', 'Cancelled')], default=('NS', 'Not Started'), max_length=50, verbose_name='Status'),
        ),
    ]
